#! /bin/sh
#
# Helper to launch the server

APP_NAME=pantos-service-node
APP_DIR=/opt/pantos/"$APP_NAME"
export PYTHONHOME=$APP_DIR
export PATH=$APP_DIR/bin:$PATH
export PYTHONUNBUFFERED=1

source_if_not_set() {
    [ ! -f "$1" ] && return
    echo "Sourcing $1"
    while IFS= read -r line || [ -n "$line" ]; do
        [ -z "$line" ] || [ "${line#\#}" != "$line" ] && continue
        key="${line%%=*}"
        echo "Checking $key"
        eval currentValue=\$$key
        [ -n "$currentValue" ] && continue
        echo "Exporting $key"
        export "$line"
    done < "$1"
}

source_if_not_set /etc/default/"$APP_NAME"

# Check if SOURCE_ENV_FILES is defined and source each file
if [ -n "$SOURCE_ENV_FILES" ]; then
    echo "Sourcing environment files: $SOURCE_ENV_FILES"
    IFS=',' read -ra FILES <<< "$SOURCE_ENV_FILES"
    for file in "${FILES[@]}"; do
        . "$file"
    done
fi

cd "$APP_DIR"

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      echo "Usage: $0 [-h|--help] [-s|--status]"
      echo "-h, --help   Show this help message"
      echo "-s, --status Start the celery worker with status monitoring"
      exit 0
      ;;
    *)
      break
      ;;
  esac
done

exec ./bin/python ./bin/start-web.py $@
