#! /bin/sh
#
# Helper to launch the celery worker

APP_NAME=pantos-service-node
APP_DIR=/opt/pantos/"$APP_NAME"
. /etc/default/"$APP_NAME"
. "$APP_DIR"/bin/activate

if [ -f "$PANTOS_ENV_FILE" ]; then
    echo "Sourcing $PANTOS_ENV_FILE"
    set -a
    . $PANTOS_ENV_FILE
    set +a
fi

exec "$APP_DIR"/bin/celery -A pantos.servicenode worker -l INFO -n pantos.servicenode -Q transfers,bids
