#! /bin/sh
#
# Helper to launch the server

APP_NAME=pantos-service-node
APP_DIR=/opt/pantos/"$APP_NAME"
export PYTHONHOME=$APP_DIR
export PATH=$APP_DIR/bin:$PATH
export PYTHONUNBUFFERED=1

source_if_not_set() {
    [ ! -f "$1" ] && return
    echo "Sourcing $1"
    while IFS= read -r line || [ -n "$line" ]; do
        [ -z "$line" ] || [ "${line#\#}" != "$line" ] && continue
        key="${line%%=*}"
        echo "Checking $key"
        eval currentValue=\$$key
        [ -n "$currentValue" ] && continue
        echo "Exporting $key"
        export "$line"
    done < "$1"
}

source_if_not_set /etc/default/"$APP_NAME"
if [ -f "$PANTOS_ENV_FILE" ]; then
    source_if_not_set "$PANTOS_ENV_FILE"
fi

cd "$APP_DIR"
exec ./bin/python ./bin/start-web.py
