#! /bin/bash

set -e

application_directory='/opt/pantos/service-node'
log_directory='/var/log/pantos'
configuration_directory='/etc/pantos'
configuration_file="${configuration_directory}/service-node-config.yml"
ssl_certificate_file="${configuration_directory}/service-node-fullchain.pem"
ssl_certificate_key_file="${configuration_directory}/service-node-privkey.pem"
system_user='pantos'

server_name=$(cat ${configuration_file} | grep 'url:' | head -1 | awk '{$1=$1;print}' | sed --expression 's/url:.*http.*\/\///;s/\/.*//')

# check if apache2 is installed on systemctl
if [ -n "$(systemctl list-units --type=service | grep apache2)" ]; then
    # stop apache2
    systemctl stop apache2
else
    echo "[pantos-service-node-server] apache2 is not installed, not stopping it"
fi

# extract server name and port
server_name_and_port=$(cat ${configuration_file} | grep 'url:' | head -1 | awk '{$1=$1;print}' | sed 's/url:.*http.*\/\///;s/\/.*//')

if [ -n "$( echo $server_name_and_port | sed -n '/:\d*/p')" ]; then
    # if port is set, extract it
    port=$(echo $server_name_and_port | sed 's/.*://')
else
    # otherwise use default port
    port=443
fi

if [ ! command -v iptables-nft &> /dev/null ]; then
    echo "[pantos-service-node-server] iptables-nft is not installed, not redirecting port"
fi
if (( $port < 1024 )) && command -v iptables-nft &> /dev/null; then
    runuser -u ${system_user} -- bash -c "source ${application_directory}/virtual-environment/bin/activate; nohup mod_wsgi-express start-server --https-port 8443 --https-only --server-name ${server_name} --ssl-certificate-file ${ssl_certificate_file} --ssl-certificate-key-file ${ssl_certificate_key_file} ${application_directory}/wsgi.py >> ${log_directory}/service-node-mod_wsgi.log 2>&1 &"
    iptables-nft -t nat -A PREROUTING -p tcp --dport $port -j REDIRECT --to-port 8443
else
    runuser -u ${system_user} -- bash -c "source ${application_directory}/virtual-environment/bin/activate; nohup mod_wsgi-express start-server --https-port ${port} --https-only --server-name ${server_name} --ssl-certificate-file ${ssl_certificate_file} --ssl-certificate-key-file ${ssl_certificate_key_file} ${application_directory}/wsgi.py >> ${log_directory}/service-node-mod_wsgi.log 2>&1 &"
fi
