name: Clean

# Collection of functions to clean any generated and no-longer-needed item

on:
    pull_request:
      #types:
      #  - closed

jobs:
    if_merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
        - uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
            with:
              disable-sudo: true
              egress-policy: audit
        
        - name: Clean Docker cache
          run: |
            target=${{ runner.os }}-buildx-v1.0-service-node-${{ github.ref_name }}
            curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/pantos-io/service-node/actions/caches?key=$target"

        
