name: Publish dev release
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and attach .deb and .whl package
    if: github.repository == 'pantos-io/servicenode'
    uses: ./.github/workflows/build.yml
    secrets: 'inherit'

  publish-docker:
    uses: ./.github/workflows/publish-docker.yaml
    if: github.repository == 'pantos-io/servicenode'
    needs: build
    secrets: 'inherit'
    with:
      tag: development
      environment: main

  test:
    needs: publish-docker
    uses: pantos-io/e2e-testing/.github/workflows/ci.yaml@main
