name: Sonar

on:
  pull_request:
    branches:
      - main

jobs:
  shared:
    uses: pantos-io/ci-workflows/.github/workflows/sonar.yml@70a45f8fe957f2f0fda1f75722e2344b1819cb40
    secrets: inherit
    
