name: Sonar

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  shared:
    #uses: pantos-io/ci-workflows/.github/workflows/sonar.yml@v1
    uses: pantos-io/ci-workflows/.github/workflows/sonar.yml@c308b64f802b40269d58c1f2492a91ddf38a049c
    secrets: inherit
    
